### ISSUE TITLE
Screenshot QR examples missing

### ISSUE THREAD

**Issue by 1oglop1** [heuer/segno-mimos#2]
Hi,
since this project is about creating QR codes it would be nice to see the some real results in images.

**Comment by heuer** [comment]
Thanks for your report. This lib is just a thin layer which emulates the API of other QR code generators and uses the main project [Segno](https://github.com/heuer/segno/). I think I won't add images here, because this project is all about adapting Segno to other APIs. But maybe some images in [Segno's documentation](https://segno.readthedocs.io/) would be nice.

I added an issue to the main project, see [#44](https://github.com/heuer/segno/issues/44)
